'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { 
  Users, 
  Loader2, 
  AlertCircle, 
  DollarSign, 
  Clock, 
  CheckCircle,
  TrendingUp
} from 'lucide-react';

interface SalesPerson {
  id: string;
  email: string;
  full_name: string;
  phone: string | null;
  referral_code: string;
  commission_type: 'recurring' | 'one_time';
  commission_rate: number;
  status: 'active' | 'inactive' | 'suspended';
  total_earnings: number;
  total_paid: number;
  pending_payout: number;
  total_users_referred: number;
  total_conversions: number;
  created_at: string;
  updated_at: string;
  last_login: string | null;
}

// Admin email - Timmy is always #000 at the top
const TIMMY_EMAIL = 'timothytitenokspam@gmail.com';

export default function SalesTeamPage() {
  const router = useRouter();
  const [salesTeam, setSalesTeam] = useState<SalesPerson[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  
  // Stats
  const [stats, setStats] = useState({
    totalRevenue: 0,
    totalPaid: 0,
    totalPending: 0,
    teamSize: 0,
  });

  useEffect(() => {
    loadSalesTeam();
  }, []);

  const loadSalesTeam = async () => {
    try {
      setLoading(true);
      setError(null);
      const response = await fetch('/api/admin/sales-team');
      
      if (!response.ok) {
        if (response.status === 403) {
          alert('⚠️ Admin Access Required');
          router.push('/signup');
          return;
        }
        throw new Error('Failed to load sales team');
      }
      
      const data = await response.json();
      const team = data.salesTeam || [];
      
      // Sort: Timmy always first (#000), then by creation date (oldest first for numbering)
      const sortedTeam = team.sort((a: SalesPerson, b: SalesPerson) => {
        // Timmy always first
        if (a.email === TIMMY_EMAIL) return -1;
        if (b.email === TIMMY_EMAIL) return 1;
        // Everyone else sorted by creation date (oldest first so numbering is consistent)
        return new Date(a.created_at).getTime() - new Date(b.created_at).getTime();
      });
      
      setSalesTeam(sortedTeam);
      
      // Calculate stats
      // Total Revenue = sum of all commissions earned
      // This represents the subscription revenue generated by sales team
      const totalCommissionsEarned = team.reduce((sum: number, p: SalesPerson) => sum + (p.total_earnings || 0), 0);
      // Revenue generated = commissions / 0.30 (using 30% recurring rate as average)
      const revenueGenerated = totalCommissionsEarned / 0.30;
      
      setStats({
        totalRevenue: revenueGenerated,
        totalPaid: team.reduce((sum: number, p: SalesPerson) => sum + (p.total_paid || 0), 0),
        totalPending: team.reduce((sum: number, p: SalesPerson) => sum + (p.pending_payout || 0), 0),
        teamSize: team.length,
      });
    } catch (err: any) {
      console.error('Error loading sales team:', err);
      setError(err.message || 'Failed to load sales team');
    } finally {
      setLoading(false);
    }
  };

  // Get permanent number for sales person - Timmy is #000, everyone else starts at #001
  const getSalesNumber = (person: SalesPerson): string => {
    // Timmy is always #000
    if (person.email === TIMMY_EMAIL) return '000';
    
    // Get all non-Timmy users sorted by creation date (oldest first)
    const nonAdminUsers = salesTeam
      .filter(s => s.email !== TIMMY_EMAIL)
      .sort((a, b) => new Date(a.created_at).getTime() - new Date(b.created_at).getTime());
    
    const position = nonAdminUsers.findIndex(s => s.id === person.id);
    // Start numbering from 001
    const number = position >= 0 ? position + 1 : 0;
    return number > 0 ? String(number).padStart(3, '0') : '???';
  };

  const formatDate = (dateString: string | null) => {
    if (!dateString) return 'Never';
    const date = new Date(dateString);
    const now = new Date();
    const diffMs = now.getTime() - date.getTime();
    const diffMins = Math.floor(diffMs / 60000);
    const diffHours = Math.floor(diffMs / 3600000);
    const diffDays = Math.floor(diffMs / 86400000);

    if (diffMins < 60) return `${diffMins}m ago`;
    if (diffHours < 24) return `${diffHours}h ago`;
    if (diffDays < 7) return `${diffDays}d ago`;
    
    return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
  };

  const getStatusBadge = (person: SalesPerson) => {
    // Timmy is always Admin
    if (person.email === TIMMY_EMAIL) {
      return (
        <span className="inline-flex items-center px-3 py-1 rounded-full border text-xs font-bold bg-purple-500/10 text-purple-400 border-purple-500/30 shadow-lg shadow-purple-500/20">
          👑 Admin
        </span>
      );
    }

    // Check if inactive for 7+ days (no login activity)
    // Use last_login if available, otherwise fall back to created_at
    const lastActive = person.last_login 
      ? new Date(person.last_login) 
      : new Date(person.created_at);
    const sevenDaysAgo = new Date();
    sevenDaysAgo.setDate(sevenDaysAgo.getDate() - 7);
    const isInactiveDueToTime = lastActive < sevenDaysAgo;

    // If suspended, always show suspended
    if (person.status === 'suspended') {
      return (
        <span className="inline-flex items-center px-3 py-1 rounded-full border text-xs font-bold bg-red-500/10 text-red-400 border-red-500/30">
          Suspended
        </span>
      );
    }

    // If inactive for 7+ days, show inactive (red)
    if (isInactiveDueToTime) {
      return (
        <span className="inline-flex items-center px-3 py-1 rounded-full border text-xs font-bold bg-red-500/10 text-red-400 border-red-500/30">
          Inactive
        </span>
      );
    }

    // Otherwise show based on status
    if (person.status === 'active') {
      return (
        <span className="inline-flex items-center px-3 py-1 rounded-full border text-xs font-bold bg-green-500/10 text-green-400 border-green-500/30">
          Active
        </span>
      );
    }

    return (
      <span className="inline-flex items-center px-3 py-1 rounded-full border text-xs font-bold bg-gray-500/10 text-gray-400 border-gray-500/30">
        Inactive
      </span>
    );
  };

  // Loading state
  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-center">
          <Loader2 className="w-16 h-16 text-green-500 animate-spin mx-auto mb-4" />
          <p className="text-gray-300 text-xl font-semibold animate-pulse">Loading sales team...</p>
        </div>
      </div>
    );
  }

  // Error state
  if (error) {
    return (
      <div className="min-h-screen flex items-center justify-center p-4">
        <div className="max-w-lg w-full">
          <div className="bg-gradient-to-br from-red-900/20 to-red-600/10 border-2 border-red-500/30 rounded-2xl p-8 backdrop-blur-xl">
            <div className="text-center">
              <div className="w-20 h-20 bg-red-500/10 rounded-full flex items-center justify-center mx-auto mb-4">
                <AlertCircle className="w-10 h-10 text-red-400" />
              </div>
              <h2 className="text-3xl font-bold text-white mb-3">Error Loading Sales Team</h2>
              <p className="text-red-300 mb-6 text-lg">{error}</p>
              <button
                onClick={loadSalesTeam}
                className="px-6 py-3 bg-green-500 hover:bg-green-600 text-white rounded-lg font-semibold transition-all"
              >
                Retry
              </button>
            </div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen p-4 md:p-8 pb-24 md:pb-8">
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <div className="mb-6">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-green-500 to-emerald-600 flex items-center justify-center shadow-lg">
                <Users className="w-8 h-8 text-white" />
              </div>
              <div>
                <h1 className="text-4xl font-bold text-white mb-1">Sales Team</h1>
                <p className="text-gray-400">Manage your sales team and track commissions</p>
              </div>
            </div>
            <div className="px-6 py-3 bg-green-500/10 border-2 border-green-500/30 rounded-xl">
              <span className="text-green-300 font-bold text-lg">{salesTeam.length} Members</span>
            </div>
          </div>
        </div>

        {/* Stats Cards */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
          {/* Team Size */}
          <div className="p-6 bg-gradient-to-br from-[#1A2647]/80 to-[#0F1629]/80 backdrop-blur-xl rounded-2xl border-2 border-purple-500/30 hover:border-purple-500/50 hover:scale-[1.03] hover:shadow-xl hover:shadow-purple-500/20 transition-all duration-300 cursor-default">
            <div className="flex items-center gap-3 mb-3">
              <div className="p-3 bg-purple-500/10 rounded-xl border border-purple-500/30">
                <Users className="w-6 h-6 text-purple-400" />
              </div>
              <div className="text-xs font-bold text-gray-400 uppercase">Team Size</div>
            </div>
            <div className="text-4xl font-black text-purple-400 mb-1">{stats.teamSize}</div>
            <div className="text-xs text-gray-400">sales members</div>
          </div>

          {/* Total Revenue Generated */}
          <div className="p-6 bg-gradient-to-br from-[#1A2647]/80 to-[#0F1629]/80 backdrop-blur-xl rounded-2xl border-2 border-green-500/30 hover:border-green-500/50 hover:scale-[1.03] hover:shadow-xl hover:shadow-green-500/20 transition-all duration-300 cursor-default">
            <div className="flex items-center gap-3 mb-3">
              <div className="p-3 bg-green-500/10 rounded-xl border border-green-500/30">
                <TrendingUp className="w-6 h-6 text-green-400" />
              </div>
              <div className="text-xs font-bold text-gray-400 uppercase">Revenue Generated</div>
            </div>
            <div className="text-4xl font-black text-green-400 mb-1">
              ${stats.totalRevenue.toLocaleString(undefined, { minimumFractionDigits: 0, maximumFractionDigits: 0 })}
            </div>
            <div className="text-xs text-gray-400">from sales referrals</div>
          </div>

          {/* Total Paid Out */}
          <div className="p-6 bg-gradient-to-br from-[#1A2647]/80 to-[#0F1629]/80 backdrop-blur-xl rounded-2xl border-2 border-blue-500/30 hover:border-blue-500/50 hover:scale-[1.03] hover:shadow-xl hover:shadow-blue-500/20 transition-all duration-300 cursor-default">
            <div className="flex items-center gap-3 mb-3">
              <div className="p-3 bg-blue-500/10 rounded-xl border border-blue-500/30">
                <CheckCircle className="w-6 h-6 text-blue-400" />
              </div>
              <div className="text-xs font-bold text-gray-400 uppercase">Total Paid Out</div>
            </div>
            <div className="text-4xl font-black text-blue-400 mb-1">
              ${stats.totalPaid.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
            </div>
            <div className="text-xs text-gray-400">commissions paid</div>
          </div>

          {/* Pending Commissions */}
          <div className="p-6 bg-gradient-to-br from-[#1A2647]/80 to-[#0F1629]/80 backdrop-blur-xl rounded-2xl border-2 border-yellow-500/30 hover:border-yellow-500/50 hover:scale-[1.03] hover:shadow-xl hover:shadow-yellow-500/20 transition-all duration-300 cursor-default">
            <div className="flex items-center gap-3 mb-3">
              <div className="p-3 bg-yellow-500/10 rounded-xl border border-yellow-500/30">
                <Clock className="w-6 h-6 text-yellow-400" />
              </div>
              <div className="text-xs font-bold text-gray-400 uppercase">Pending Commissions</div>
            </div>
            <div className="text-4xl font-black text-yellow-400 mb-1">
              ${stats.totalPending.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
            </div>
            <div className="text-xs text-gray-400">awaiting payout</div>
          </div>
        </div>

        {/* Sales Team Table */}
        <div className="bg-[#1A2647]/40 backdrop-blur-xl rounded-2xl border-2 border-gray-700/30 overflow-hidden shadow-2xl">
          <div className="overflow-x-auto">
            <table className="w-full table-fixed">
              <thead>
                <tr className="bg-[#0B1437] border-b-2 border-gray-700/50">
                  <th className="px-4 py-4 text-center text-xs font-bold text-gray-400 uppercase tracking-wider" style={{ width: '8%' }}>
                    #
                  </th>
                  <th className="px-6 py-4 text-left text-xs font-bold text-gray-400 uppercase tracking-wider" style={{ width: '22%' }}>
                    Name
                  </th>
                  <th className="px-6 py-4 text-left text-xs font-bold text-gray-400 uppercase tracking-wider" style={{ width: '30%' }}>
                    Email
                  </th>
                  <th className="px-6 py-4 text-center text-xs font-bold text-gray-400 uppercase tracking-wider" style={{ width: '20%' }}>
                    Last Active
                  </th>
                  <th className="px-6 py-4 text-center text-xs font-bold text-gray-400 uppercase tracking-wider" style={{ width: '20%' }}>
                    Status
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-700/30">
                {salesTeam.length === 0 ? (
                  <tr>
                    <td colSpan={5} className="px-6 py-16 text-center">
                      <Users className="w-16 h-16 text-gray-600 mx-auto mb-4" />
                      <p className="text-gray-400 text-lg">No sales team members yet</p>
                      <p className="text-gray-500 text-sm mt-1">Sales people will appear here after they sign up</p>
                    </td>
                  </tr>
                ) : (
                  salesTeam.map((person) => (
                    <tr 
                      key={person.id}
                      onClick={() => router.push(`/admin/sales-team/${person.id}`)}
                      className="hover:bg-[#1A2647]/60 transition-all cursor-pointer group"
                    >
                      <td className="px-4 py-4 text-center">
                        <span className="text-lg font-mono font-bold text-gray-500 group-hover:text-green-400 transition-colors">
                          #{getSalesNumber(person)}
                        </span>
                      </td>
                      <td className="px-6 py-4">
                        <div className="font-semibold text-white group-hover:text-green-300 transition-colors">
                          {person.full_name || 'No Name'}
                        </div>
                      </td>
                      <td className="px-6 py-4">
                        <div className="text-gray-400 text-sm truncate">{person.email}</div>
                      </td>
                      <td className="px-6 py-4 text-center">
                        <span className="text-gray-400 text-sm">
                          {formatDate(person.last_login || person.created_at)}
                        </span>
                      </td>
                      <td className="px-6 py-4 text-center">
                        {getStatusBadge(person)}
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
}
