import type {
  UserAdmin,
  LeadSource,
  LeadStats,
  BillingInfo,
  DialerRun,
  Appointment,
  AdminLog,
  CallRecord,
} from '@/types/admin';

// Helper to generate dates
const daysAgo = (days: number) => {
  const date = new Date();
  date.setDate(date.getDate() - days);
  return date.toISOString();
};

const hoursAgo = (hours: number) => {
  const date = new Date();
  date.setHours(date.getHours() - hours);
  return date.toISOString();
};

// Mock Users
export const mockUsers: UserAdmin[] = [
  {
    id: '1',
    name: 'John Sterling',
    email: 'john@example.com',
    phone: '+1234567890',
    joinedAt: daysAgo(45),
    plan: 'Pro',
    isTrial: false,
    trialDaysLeft: 0,
    status: 'active',
    lastLoginAt: hoursAgo(2),
    totalLogins: 143,
    totalSpend: 2847.50,
    currentCallBalance: 156.75,
    autoRefillEnabled: true,
    leadSources: 3,
    totalLeads: 1250,
    dialerAutomationEnabled: true,
    dailyBudget: 50,
    todaySpend: 23.45,
    scheduleTime: '09:00-17:00',
    scheduleDays: 'Mon-Fri',
    dialerHealth: 'good',
  },
  {
    id: '2',
    name: 'Sarah Mitchell',
    email: 'sarah@example.com',
    phone: '+1234567891',
    joinedAt: daysAgo(12),
    plan: 'FreeTrial',
    isTrial: true,
    trialDaysLeft: 18,
    status: 'active',
    lastLoginAt: hoursAgo(5),
    totalLogins: 34,
    totalSpend: 0,
    currentCallBalance: 25.00,
    autoRefillEnabled: false,
    leadSources: 1,
    totalLeads: 200,
    dialerAutomationEnabled: false,
    dailyBudget: 25,
    todaySpend: 0,
    scheduleTime: '10:00-16:00',
    scheduleDays: 'Mon-Fri',
    dialerHealth: 'good',
  },
  {
    id: '3',
    name: 'Michael Chen',
    email: 'michael@example.com',
    joinedAt: daysAgo(90),
    plan: 'VIP',
    isTrial: false,
    trialDaysLeft: 0,
    status: 'active',
    lastLoginAt: hoursAgo(1),
    totalLogins: 412,
    totalSpend: 12450.00,
    currentCallBalance: 450.25,
    autoRefillEnabled: true,
    leadSources: 8,
    totalLeads: 5000,
    dialerAutomationEnabled: true,
    dailyBudget: 200,
    todaySpend: 145.80,
    scheduleTime: '08:00-20:00',
    scheduleDays: 'Mon-Sun',
    dialerHealth: 'good',
  },
  {
    id: '4',
    name: 'Emily Rodriguez',
    email: 'emily@example.com',
    phone: '+1234567893',
    joinedAt: daysAgo(60),
    plan: 'Starter',
    isTrial: false,
    trialDaysLeft: 0,
    status: 'active',
    lastLoginAt: daysAgo(3),
    totalLogins: 87,
    totalSpend: 567.30,
    currentCallBalance: 12.50,
    autoRefillEnabled: false,
    leadSources: 2,
    totalLeads: 450,
    dialerAutomationEnabled: false,
    dailyBudget: 15,
    todaySpend: 8.20,
    scheduleTime: '09:00-17:00',
    scheduleDays: 'Mon-Fri',
    dialerHealth: 'warning',
  },
  {
    id: '5',
    name: 'David Thompson',
    email: 'david@example.com',
    joinedAt: daysAgo(150),
    plan: 'Pro',
    isTrial: false,
    trialDaysLeft: 0,
    status: 'suspended',
    lastLoginAt: daysAgo(15),
    totalLogins: 245,
    totalSpend: 3200.00,
    currentCallBalance: 0,
    autoRefillEnabled: false,
    leadSources: 4,
    totalLeads: 1800,
    dialerAutomationEnabled: false,
    dailyBudget: 40,
    todaySpend: 0,
    scheduleTime: '09:00-17:00',
    scheduleDays: 'Mon-Fri',
    dialerHealth: 'error',
  },
  {
    id: '6',
    name: 'Jessica Parker',
    email: 'jessica@example.com',
    phone: '+1234567895',
    joinedAt: daysAgo(8),
    plan: 'FreeTrial',
    isTrial: true,
    trialDaysLeft: 22,
    status: 'active',
    lastLoginAt: hoursAgo(12),
    totalLogins: 18,
    totalSpend: 0,
    currentCallBalance: 25.00,
    autoRefillEnabled: false,
    leadSources: 1,
    totalLeads: 150,
    dialerAutomationEnabled: true,
    dailyBudget: 20,
    todaySpend: 5.60,
    scheduleTime: '10:00-18:00',
    scheduleDays: 'Mon-Fri',
    dialerHealth: 'good',
  },
];

// Mock Lead Sources
export const mockLeadSources: LeadSource[] = [
  {
    id: 'ls1',
    userId: '1',
    name: 'California Leads Q4',
    type: 'GoogleSheet',
    lastSyncedAt: hoursAgo(2),
    totalRows: 500,
    validRows: 485,
    invalidRows: 15,
    status: 'ok',
  },
  {
    id: 'ls2',
    userId: '1',
    name: 'Texas Prospects',
    type: 'CSV',
    lastSyncedAt: daysAgo(1),
    totalRows: 350,
    validRows: 340,
    invalidRows: 10,
    status: 'ok',
  },
  {
    id: 'ls3',
    userId: '3',
    name: 'National Campaign',
    type: 'GoogleSheet',
    lastSyncedAt: hoursAgo(1),
    totalRows: 2000,
    validRows: 1950,
    invalidRows: 50,
    status: 'ok',
  },
  {
    id: 'ls4',
    userId: '2',
    name: 'Local Leads',
    type: 'CSV',
    lastSyncedAt: daysAgo(5),
    totalRows: 200,
    validRows: 180,
    invalidRows: 20,
    status: 'error',
  },
];

// Mock Lead Stats
export const mockLeadStats: LeadStats[] = mockUsers.map((user) => ({
  userId: user.id,
  totalLeads: user.totalLeads,
  freshLeads: Math.floor(user.totalLeads * 0.4),
  agedLeads: Math.floor(user.totalLeads * 0.35),
  deadLeads: Math.floor(user.totalLeads * 0.15),
  callbacks: Math.floor(user.totalLeads * 0.1),
  pickupRate: 0.35 + Math.random() * 0.3,
  conversionRate: 0.05 + Math.random() * 0.15,
  avgCallDurationSec: 120 + Math.floor(Math.random() * 180),
  leadsAttemptedToday: Math.floor(user.totalLeads * 0.05),
  callsToday: Math.floor(user.todaySpend / 0.15),
  minutesToday: Math.floor(user.todaySpend / 0.15 * 2.5),
}));

// Mock Billing Info
export const mockBillingInfo: BillingInfo[] = mockUsers.map((user) => ({
  userId: user.id,
  stripeCustomerId: `cus_${user.id}${Math.random().toString(36).substr(2, 9)}`,
  stripeSubId: user.isTrial ? undefined : `sub_${user.id}${Math.random().toString(36).substr(2, 9)}`,
  plan: user.plan,
  subStatus: user.isTrial ? 'trialing' : user.status === 'active' ? 'active' : 'canceled',
  renewalDate: user.isTrial ? daysAgo(-user.trialDaysLeft) : daysAgo(-30),
  paymentMethodStatus: user.status === 'suspended' ? 'expired' : user.isTrial ? 'missing' : 'valid',
  last4: user.isTrial ? undefined : `${Math.floor(1000 + Math.random() * 9000)}`,
  brand: user.isTrial ? undefined : ['Visa', 'Mastercard', 'Amex'][Math.floor(Math.random() * 3)],
  lifetimeRevenue: user.totalSpend,
  monthRevenue: Math.floor(user.totalSpend / 3),
  callBalancePurchased: user.totalSpend * 0.8,
  chargebacks: user.status === 'suspended' ? 1 : 0,
  autoRefillEnabled: user.autoRefillEnabled,
  lastAutoRefillAt: user.autoRefillEnabled ? hoursAgo(48) : undefined,
  lastAutoRefillAmount: user.autoRefillEnabled ? 25.00 : undefined,
  autoRefillFailures: 0,
}));

// Mock Dialer Runs
export const mockDialerRuns: DialerRun[] = [
  {
    id: 'dr1',
    userId: '1',
    userName: 'John Sterling',
    startedAt: hoursAgo(3),
    stoppedAt: hoursAgo(1),
    status: 'completed',
    calls: 45,
    minutes: 112,
    appointments: 3,
    stopReason: 'Daily budget reached',
  },
  {
    id: 'dr2',
    userId: '3',
    userName: 'Michael Chen',
    startedAt: hoursAgo(2),
    status: 'running',
    calls: 87,
    minutes: 215,
    appointments: 7,
  },
  {
    id: 'dr3',
    userId: '6',
    userName: 'Jessica Parker',
    startedAt: hoursAgo(4),
    stoppedAt: hoursAgo(3),
    status: 'completed',
    calls: 12,
    minutes: 28,
    appointments: 1,
  },
  {
    id: 'dr4',
    userId: '4',
    userName: 'Emily Rodriguez',
    startedAt: hoursAgo(6),
    stoppedAt: hoursAgo(5),
    status: 'budget_reached',
    calls: 8,
    minutes: 18,
    appointments: 0,
    stopReason: 'Daily budget limit reached',
  },
  {
    id: 'dr5',
    userId: '1',
    userName: 'John Sterling',
    startedAt: daysAgo(1),
    stoppedAt: daysAgo(1),
    status: 'completed',
    calls: 52,
    minutes: 128,
    appointments: 4,
  },
];


// Mock Appointments
export const mockAppointments: Appointment[] = [
  {
    id: 'apt1',
    userId: '1',
    userName: 'John Sterling',
    leadName: 'Robert Johnson',
    phone: '+1555123456',
    dateTime: hoursAgo(-24),
    source: 'AI Dialer',
    status: 'upcoming',
  },
  {
    id: 'apt2',
    userId: '3',
    userName: 'Michael Chen',
    leadName: 'Linda Williams',
    phone: '+1555123457',
    dateTime: hoursAgo(-48),
    source: 'AI Dialer',
    status: 'upcoming',
  },
  {
    id: 'apt3',
    userId: '1',
    userName: 'John Sterling',
    leadName: 'Mark Davis',
    phone: '+1555123458',
    dateTime: daysAgo(2),
    source: 'AI Dialer',
    status: 'completed',
  },
  {
    id: 'apt4',
    userId: '6',
    userName: 'Jessica Parker',
    leadName: 'Sarah Miller',
    phone: '+1555123459',
    dateTime: daysAgo(1),
    source: 'Manual',
    status: 'no_show',
  },
  {
    id: 'apt5',
    userId: '3',
    userName: 'Michael Chen',
    leadName: 'Tom Anderson',
    phone: '+1555123460',
    dateTime: hoursAgo(-6),
    source: 'AI Dialer',
    status: 'upcoming',
  },
];

// Mock Admin Logs
export const mockAdminLogs: AdminLog[] = [
  {
    id: 'log1',
    ts: hoursAgo(1),
    level: 'info',
    scope: 'dialer',
    message: 'Dialer automation started successfully',
    userId: '3',
    userName: 'Michael Chen',
  },
  {
    id: 'log2',
    ts: hoursAgo(2),
    level: 'warn',
    scope: 'billing',
    message: 'Payment method expiring soon',
    userId: '4',
    userName: 'Emily Rodriguez',
  },
  {
    id: 'log3',
    ts: hoursAgo(3),
    level: 'error',
    scope: 'leads',
    message: 'Lead source sync failed: Invalid API key',
    userId: '2',
    userName: 'Sarah Mitchell',
  },
  {
    id: 'log4',
    ts: hoursAgo(4),
    level: 'info',
    scope: 'user',
    message: 'User logged in from new device',
    userId: '1',
    userName: 'John Sterling',
  },
  {
    id: 'log5',
    ts: hoursAgo(5),
    level: 'info',
    scope: 'billing',
    message: 'Subscription renewed successfully',
    userId: '3',
    userName: 'Michael Chen',
  },
  {
    id: 'log6',
    ts: hoursAgo(6),
    level: 'error',
    scope: 'system',
    message: 'Webhook delivery failed: Timeout',
  },
  {
    id: 'log7',
    ts: hoursAgo(12),
    level: 'warn',
    scope: 'dialer',
    message: 'Daily budget limit approaching',
    userId: '1',
    userName: 'John Sterling',
  },
];

// Mock Call Records
export const mockCallRecords: CallRecord[] = Array.from({ length: 20 }, (_, i) => ({
  id: `call${i + 1}`,
  userId: mockUsers[i % mockUsers.length].id,
  leadName: ['James Smith', 'Mary Johnson', 'Robert Williams', 'Patricia Brown', 'Michael Davis'][i % 5],
  phone: `+155512345${60 + i}`,
  startedAt: hoursAgo(i * 2),
  duration: 60 + Math.floor(Math.random() * 240),
  outcome: ['answered', 'no_answer', 'voicemail', 'busy', 'appointment_booked'][i % 5],
  cost: 0.10 + Math.random() * 0.50,
  recordingUrl: i % 3 === 0 ? 'https://example.com/recording.mp3' : undefined,
}));

// Daily stats for charts
export const mockDailyStats = Array.from({ length: 7 }, (_, i) => ({
  date: daysAgo(6 - i),
  calls: 50 + Math.floor(Math.random() * 150),
  minutes: 120 + Math.floor(Math.random() * 400),
  revenue: 150 + Math.floor(Math.random() * 350),
  appointments: 2 + Math.floor(Math.random() * 8),
}));

